### PR TITLE
use index instead of id

### PR DESCRIPTION
**Pull request by ChristopheMees**

### CODE REVIEW

**Comment by ccantill** [comment]
Keep in mind that row indexes change when the sorting changes or groups are collapsed/expanded. Id is a more stable value to work with.
And if you're going to use idx anyway, you'll want to change the selector on line 39 too.

**Comment by ChristopheMees** [comment]
For our current use case it's easier to use the index since we can just get it from the array of rows. Might be better to support both then and pass it as an option for the extension.

**Comment by ccantill** [comment]
Just a heads up; if you're relying on data-row-idx, there was a bug where inserting or removing rows (e.g. when expanding/collapsing groups) would not update the row indexes of the rows after the ones being removed or inserted (so you'd get index gaps or reused indexes). I fixed this on our development branch; https://github.com/unifly-aero/powergrid/pull/38

**Comment by ChristopheMees** [comment]
https://github.com/PearlChain/powergrid/pull/23

**Pull request closed without merging**
